# ==========================
# Application
# ==========================
spring.application.name=ordermanagement

# ==========================
# Server
# ==========================
server.port=8080

# ==========================
# Database
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/order_management_db
spring.datasource.username=postgres
spring.datasource.password=DB_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Jackson
# ==========================
spring.jackson.serialization.write-dates-as-timestamps=false

# ==========================
# Logging
# ==========================
logging.level.root=INFO
logging.level.com.oms=DEBUG
logging.level.org.springframework.data=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG